name: Build Docker Image to Aliyun

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
env:
  REGISTRY: registry.cn-chengdu.aliyuncs.com
  NAMESPACE: mirror_d
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $REGISTRY
        
        # check version
        python3 .github/workflows/check_image_version.py
        
        set -ex
        
        # build on arm64
        cat to_pull.txt | sed '/^\s*$/d;/^#/d' | awk '{print "docker pull --platform linux/arm64 " $1}' | sh
        cat to_pull.txt | sed '/^\s*$/d;/^#/d' | awk '{print "docker tag " $1 " '"$REGISTRY/$NAMESPACE/"'" $2 "-arm64"}' | sh
        cat to_pull.txt | sed '/^\s*$/d;/^#/d' | awk '{print "docker push " "'"$REGISTRY/$NAMESPACE/"'" $2 "-arm64"}' | sh
  
        # build on amd64
        cat to_pull.txt | sed '/^\s*$/d;/^#/d' | awk '{print "docker pull --platform linux/amd64 " $1}' | sh
        cat to_pull.txt | sed '/^\s*$/d;/^#/d' | awk '{print "docker tag " $1 " '"$REGISTRY/$NAMESPACE/"'" $2 "-amd64"}' | sh
        cat to_pull.txt | sed '/^\s*$/d;/^#/d' | awk '{print "docker push " "'"$REGISTRY/$NAMESPACE/"'" $2 "-amd64"}' | sh

        # send notification
        python3 .github/workflows/send_email.py