name: build Docker Image to aliyun

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: |
        docker login -u du_peng -p dupeng01 registry.cn-chengdu.aliyuncs.com
        sh pull.sh
