name: Build Docker Image to Aliyun

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
env:
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker images
        run: |
          set -ex
          source registry_env.sh
          docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $REGISTRY
          docker buildx create --name=container --driver=docker-container --use --bootstrap

          # build images
          python3 .github/workflows/docker_build.py
