name: Build Docker Image to Aliyun

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
env:
  REGISTRY_USER: "${{ secrets.REGISTRY_USER }}"
  REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker images
        run: |
          set -ex
          source registry_env.sh
          # docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
          echo $REGISTRY_PASSWORD | docker login $REGISTRY -u $REGISTRY_USER --password-stdin
          docker buildx create --name=container --driver=docker-container --use --bootstrap

          # build images
          python3 .github/workflows/docker_build.py
