name: Copy DockerHub Image to Aliyun Registry

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
env:
#  REGISTRY: registry.cn-chengdu.aliyuncs.com
#  NAMESPACE: mirror_d
#  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
#  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  set-up-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.ALIYUN_REGISTRY_USER }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}



  docker:

    runs-on: ubuntu-latest
    needs: set-up-docker
#    strategy:
#      matrix:
#        tag: [mirror_d/alpine, mirror_d/busybox]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Dockerfile
        run: |

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
#          file: ${{  }}
          tags: alpine